version: 0.2

phases:
  install:
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install -i /usr/local/aws-cli -b /usr/local/bin --update
      - pip3 install git+https://github.com/aws-greengrass/aws-greengrass-gdk-cli.git@v1.6.2
      - curl "https://pipescript.s3.eu-west-1.amazonaws.com/deploy-components.sh" -o "deploy-components.sh"
  build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - AWS_REGION=eu-west-1
      # - COMPONENT_NAME=$(cat gdk-config.json | jq -r '.component | keys[]')
      - chmod +x ./deploy-components.sh
      - sh -x ./deploy-components.sh ${AWS_ACCOUNT_ID} ${AWS_REGION} ${COMPONENT_NAME} ${IOT_THING_GROUP} ${DEPLOYMENT_NAME}
